version: "2.22"
services:

  postgres:
    container_name: "pgs_chart"
    image: postgres:latest
    environment:
      POSTGRES_DB: "chart"
      POSTGRES_USER: "echopguser"
      POSTGRES_PASSWORD: "pgpw4echo"
      PGDATA: "/var/lib/postgresql/data"
      